// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  var BaseController, LoginView;
  LoginView = require("views/login");
  BaseController = require("controllers/base");
  return new aJazz.Route({
    enter: function(app, query, forward) {
      var view;
      view = app.getView("login");
      if (view == null) {
        view = new LoginView({
          controllers: {
            login: new BaseController()
          }
        });
        app.setView("login", view);
      }
      return app.bindView("page", view, {
        forward: forward
      });
    },
    level: 0
  });
});
