// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  return aJazz.App.extend({
    className: "viewport",
    template: template(require("templates/game.html")),
    routes: {
      "": "routes/login",
      "index": "routes/index"
    }
  });
});
