// Generated by CoffeeScript 1.7.1

/*
Index page view class
 */
define(function(require, exports, module) {
  var TransView;
  TransView = require("views/TransView");
  return TransView.extend({
    className: "page",
    template: template(require("templates/index.html"))
  });
});
