// Generated by CoffeeScript 1.7.1

/*
Login page view class
 */
define(function(require, exports, module) {
  var MyTabView, TransView;
  TransView = require("views/TransView");
  MyTabView = require("views/mytab");
  return TransView.extend({
    className: "page",
    template: template(require("templates/login.html")),
    events: {
      "click|.role-log": function(e) {
        alert("this is log");
      }
    },
    render: function() {
      TransView.prototype.render.call(this);
      this.setView("tab", new MyTabView(), true);
    },
    init: function(options) {
      var loginController;
      loginController = this.getController("login");
      loginController.on("success", function(e, response) {
        this.log = typeof JSON !== "undefined" && JSON !== null ? JSON.stringify(response) : response.toString();
        this.render$(".role-log", true);
        this.bindData("usr", (new Date()).toString());
      }, this);
      this.on("transEnd", function(e, visible, forward) {
        forward && loginController.send({
          usr: (this.$("input")).val()
        });
      });
      TransView.prototype.init.call(this, options);
    }
  });
});
