// Generated by CoffeeScript 1.7.1

/*
simple text msg view class
 */
define(function(require, exports, module) {
  return aJazz.View.extend({
    template: function() {
      return this.options.msg;
    }
  });
});
